### ISSUE TITLE
ONEDAY 利用規約の未決事項を決めましょう

### ISSUE THREAD

**Issue by takatan46** [omamori-inc/oneday-userrule#5]
ONEDAY 利用規約を再作成する中で、未決事項を洗い出しました。
少し量が多いので、issuesとして起案します。ここで決めた後、利用規約に反映してPRでレビュー依頼する予定です。
@CP-NAKAMURA @Daisuke-Yoshida0420 （@ShuntaIto ）よろしくです。

※未決事項：認識合わせが必要な箇所や議論が必要な部分も含めています。

> 入塾手続き
- [ ] 入塾金の有無
- [ ]  有なら金額（10,000円+税?）

> 契約期間
- [ ] 退塾の申し出（継続の拒否）の期日：資料は前月の15日まで

> 料金等
- [ ] 授業プランやサポートプラン変更の申し出方法や手続きの流れ
- [ ] 月途中での入塾する場合、授業料金は割って請求するのか
- [ ] 割るのではれば、算出方法
- [ ] 料金・諸費用の滞納への対処

> 返金・クーリングオフ
- [ ] 決済手段として銀行振込を受け付けるか（決済手段の確定）
- [ ] クーリングオフの記載有無（契約をオンラインで実施する場合は、通信販売に該当するため適用外）

> 授業等の遅刻・欠席・振替について
- [ ] 授業の遅刻・欠席の連絡手段とその期日（やむおえない場合の例外も想定して記載する）
- [ ] 授業振替の連絡（届出）手段とその期日（資料では振替は1時間前となっている）
- [ ] 授業振替の実施期限（資料では振替は１ヶ月以内となっている）
- [ ] 振替しない場合の条件を洗い出し

> 休校
- [ ] 休校の周知手段
- [ ] 休校の周知の期日
- [ ] 休校の場合の保証返金（既存案：原則振替で、やむおえず振替できなかったら授業に相当する料金は返金）

> 休会
- [ ] 休会の連絡（届出）手段
- [ ] 休会の連絡（届出）期日
- [ ] 休会の最大期間 （超えた場合の処置も決める）

> 退塾
- [ ] 中途退塾の連絡（届出）期日：資料は前月の15日まで（直前すぎるとStripe決済の手続きが間に合わないと思う）
- [ ] 退塾となる日は、提出した日の翌月末か？

> 施設利用

入れたい内容があればこの条項を追加します。例えば、
1. 筆記用具やノートは持ってきてね、とか
2. 備品の取り扱いとか（免責に記載はあり）
3. 営業時間とか
4. その他：施設を利用する際の注意点や必ず伝えておきたいこと

> 知的財産権等

ONEDAY独自の作成物あるか？
今後予定があれば条項追加しようと思っています。

> 免責事項
- [ ] 偏差値上がる等の学習能力向上あたりの保証はできない旨とか入れるものなのでしょうか？

**Comment by Daisuke-Yoshida0420** [comment]
バタバタしてて追えてませんでした。ONEDAYの資料の方は作り直していますが、利用規約を以前の作成段階から直していないので、最新の内容は現在の資料の方ですので、資料に記載しているものはそちらに合わせてください。それ以外は既存の利用規約に記載されている内容に準拠します。挙げられた項目のうちいくつかはすでに利用規約に記載されているので、特に異論がなければそのままでいいと考えています。

### 入塾手続き
- 入塾金は一旦なしでいいかなって思ってます。Omamori の IT インフラを使って登録作業を進めるので、インフラの利用料を入塾金で賄うのはありですが、少なくともβ版相当の現段階ではそれもいらないかなと。
- ある程度事業仮説の検証が済んだら、入塾金を11000円で設定するのはありだと思います。クラウドサイン等の利用料の問題はこれで解決可能かと。

### 契約期間
- 契約期間は一ヶ月更新（各月1日～末日）とします。
- 退塾の申し出（継続の拒否）の期日：資料に合わせて前月の15日までにします。今の利用規約上では前月末までにしていますが、1ヶ月前だと使う側が早めに言わないといけない点で負担が大きいかなと判断しました。
- 授業プランやサポートプラン変更は翌月から反映する流れにします。公式 LINE or Slack で申し出を行い、こちらが受理した段階でプラン変更が完了するものとします。
 
### 料金等

- 月の途中で入塾する場合、月額料金を予定される授業回数で割って一回分の授業料を算出し、実施した授業回数分をかけてその月の利用料とします。例えば週1のプランで月2万円だった場合、月に4コマ実施されることが多いので1コマあたり5000円になります。このうち契約開始の都合で2コマしか受けられなかった場合、初月の利用料は5000×2=10000円となります。
- 決済手段ですが、通塾生の場合のみ銀行振込の選択肢を残します。オンライン生の場合は全てStripeのみで統一します。
 クーリングオフの記載有無（契約をオンラインで実施する場合は、通信販売に該当するため適用外）
- 料金・諸費用の滞納への対処は規約の第6条に、返金・クーリングオフの記載は第7条に書いてあります。ただし、1回でも授業を行った場合はクーリングオフの対象外にしたい（期間内にまとめて数回授業を受けてからクーリングオフをされると、数回分の講師の人件費だけがかかって赤字になってしまうので）のですが、そういうことは可能ですか？

### 授業等の遅刻・欠席・振替
- 授業等の遅刻・欠席・振替については第8条に書いてある通りです。資料との不整合もないかと思うので、特段問題がなければこのままでいいかと思います。
- 連絡手段は公式 LINE か Slack を使用します。

### 休校
- 定例行事の場合の休校は公式 LINE か Slack を使用して、1か月前までに周知を行います。定例の休校では返金も振替もしません。
- 臨時休校の場合も周知方法は同じで、わかり次第即時的に周知します。この場合は原則振替で、やむおえず振替できなかったら授業に相当する料金は返金します。

### 休塾・退塾
- 退塾は5条、休塾は9条に書いてあります。届出手段は休塾届・退塾届の提出としているので、所定のフォームを提出して受理した段階で手続き成立とします。
- 休会の最大期間は6か月となっていますが、正直ちょっと長いかなと思っています。3か月で良いかも。また、自動で復塾というのもやめたい人にとってはあまり親切じゃないので、期間を超えて復塾の予定がない場合が自動で退塾のほうがいいかもしれません。ぎりぎりまで休塾してる子が戻ってくることはまずないですからね。

### 施設利用
- 教室の汚損等の条項はすでに11条に記載したはずなので、抜け漏れがないかだけ確認してください。
- 挙げてもらった項目は確かに大事なんだけど、利用規約に入れるかどうかは悩ましいかな……契約書の方に記載でもいいかも。

### 知的財産権等
- チェックテストとか、目標管理シートはこれに当たりますね。なので知財の条項はいる。

### 免責事項
「偏差値上がる等の学習能力向上あたりの保証はできない」という趣旨のものは入れたほうが良いかも。

**Comment by takatan46** [comment]
@Daisuke-Yoshida0420 対応サンキューです。

以下で作成します。

### 入塾手続き

- 入塾金なし

### 契約期間

- 全て了解です

### 料金等

- 了解です。月によっては4回5回と回数が変わることがありますが、公平に、入塾該当月に実施する回数を分母とするような文言にします。
- 決済も了解です。
- クーリングオフの件、吉田の言ったことはできないです。無条件に解約できる旨を法律で定められています。今回、通信販売に該当するか否かが、明記する論点になります。（例えば、全て通信販売ならクーリングオフ適用外のため、明記なし。）

### 授業等の遅刻・欠席・振替
- 了解です。
- 1点、振替授業の届出期日ですが、**授業予定日の3日前まで**で決定ですか？（資料には無かったです）

### 休校
- 了解です。

### 休塾・退塾
- 該当する授業開始の1時間前までの連絡、了解です。
- 休会3か月で、超えた場合は自動退塾で作成します。休会金の発生有無はどうしますか？（管理手数料取ってもいい気もしますが、まあ相談しましょう）
- 
### 施設利用
- この条項は無しで行きます。免責や禁止行為の部分に入れておきます。

### 知的財産権等
- 了解です。
- 
### 免責事項

- 了解です。ただ、これ慣習とかもあると思うので、MTGで詳しく教えてください。
